# Generated by Django 4.1.13 on 2025-04-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_dataobat_slug_alter_dataobat_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
