# Generated by Django 4.1.13 on 2025-04-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_dataobat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataobat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obat_images/'),
        ),
    ]
