# Generated by Django 4.1.13 on 2025-04-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_dataobat_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='foto',
            field=models.ImageField(upload_to='obat_images/'),
        ),
        migrations.AlterField(
            model_name='dataobat',
            name='harga',
            field=models.PositiveIntegerField(),
        ),
    ]
