# Generated by Django 4.2.20 on 2025-04-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_dataobat_harga'),
        ('adminapp', '0006_dataobat_foto'),
    ]

    operations = [
    ]
