# Generated by Django 4.1.13 on 2025-04-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_dataobat_harga'),
        ('adminapp', '0006_dataobat_foto'),
    ]

    operations = [
    ]
