# Generated by Django 5.2 on 2025-04-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_dataobat_foto_alter_dataobat_harga'),
        ('adminapp', '0007_merge_0003_alter_dataobat_harga_0006_dataobat_foto'),
    ]

    operations = [
    ]
