# Generated by Django 5.2 on 2025-05-03 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_merge_20250428_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.dataobat')),
            ],
        ),
    ]
