# Generated by Django 4.1.13 on 2025-04-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0003_resepdokter_nama_pasien'),
    ]

    operations = [
        migrations.AddField(
            model_name='resepdokter',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
