# Generated by Django 5.1.7 on 2025-05-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0004_resepdokter_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resepdokter',
            name='nama_pasien',
        ),
        migrations.RemoveField(
            model_name='resepdokter',
            name='slug',
        ),
    ]
