# Generated by Django 4.1.13 on 2025-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0004_resepdokter_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resepdokter',
            old_name='nama_pasien',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='resepdokter',
            name='slug',
        ),
        migrations.AddField(
            model_name='resepdokter',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]