# Generated by Django 4.1.13 on 2025-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0005_rename_nama_pasien_resepdokter_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resepdokter',
            old_name='dokter',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='resepdokter',
            name='obat',
        ),
        migrations.RemoveField(
            model_name='resepdokter',
            name='tanggal',
        ),
        migrations.RemoveField(
            model_name='resepdokter',
            name='tanggal_upload',
        ),
        migrations.AlterField(
            model_name='resepdokter',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
