# Generated by Django 4.1.13 on 2025-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0006_rename_dokter_resepdokter_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resepdokter',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
