# Generated by Django 4.2.20 on 2025-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarobat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obat',
            name='deskripsi',
        ),
        migrations.AlterField(
            model_name='obat',
            name='kategori',
            field=models.CharField(choices=[('Antibiotik', 'Antibiotik'), ('Vitamin', 'Vitamin'), ('Analgesik', 'Analgesik')], default='Vitamin', max_length=20),
        ),
    ]
