# Generated by Django 4.2.20 on 2025-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarobat', '0002_remove_obat_deskripsi_alter_obat_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='obat',
            name='cara_pemakaian',
            field=models.TextField(default='Aturan pakai belum ditentukan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='gambar',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obat',
            name='kategori',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Kapsul', 'Kapsul'), ('Sirup', 'Sirup'), ('Salep', 'Salep')], max_length=50),
        ),
        migrations.AlterField(
            model_name='obat',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obat',
            name='stok',
            field=models.PositiveIntegerField(),
        ),
    ]
