# Generated by Django 4.2.20 on 2025-04-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarobat', '0003_obat_cara_pemakaian_obat_gambar_alter_obat_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='gambar',
            field=models.ImageField(upload_to=''),
        ),
    ]
