# Generated by Django 4.1.13 on 2025-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resepdokter',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resepdokter',
            name='dokter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resepdokter',
            name='obat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resepdokter',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
