# Generated by Django 4.1.13 on 2025-04-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resepapp', '0002_resepdokter_catatan_resepdokter_dokter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resepdokter',
            name='nama_pasien',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
