# Generated by Django 4.2.20 on 2025-04-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftarobat', '0004_alter_obat_gambar'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembelian', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('obat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftarobat.obat')),
            ],
        ),
        migrations.DeleteModel(
            name='LogAktivitas',
        ),
    ]
