# Generated by Django 4.2.20 on 2025-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_historypembelian_delete_logaktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypembelian',
            name='nama_pembeli',
            field=models.CharField(default='Anonim', max_length=100),
            preserve_default=False,
        ),
    ]
