# Generated by Django 5.2 on 2025-05-04 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('kontak_pemesan', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('waktu_beli', models.DateTimeField(default=django.utils.timezone.now)),
                ('waktu_bayar', models.DateTimeField()),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=100)),
                ('harga', models.PositiveIntegerField()),
                ('keterangan', models.TextField()),
                ('jumlah', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='riwayat.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='pembelian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='riwayat.pembelian'),
        ),
    ]
