# Generated by Django 5.2 on 2025-05-05 11:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat', '0002_pembelian_gambar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pembelian',
        ),
        migrations.RemoveField(
            model_name='iteminvoice',
            name='invoice',
        ),
        migrations.CreateModel(
            name='RiwayatPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('kontak_pembeli', models.CharField(max_length=100)),
                ('nama_obat', models.CharField(max_length=120)),
                ('harga_obat', models.PositiveIntegerField()),
                ('jumlah_beli', models.PositiveIntegerField()),
                ('total_harga', models.PositiveIntegerField()),
                ('tanggal_beli', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pembelian',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='ItemInvoice',
        ),
    ]
