# Generated by Django 4.1.13 on 2025-05-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regisapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
