services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data:

networks:
  default:
    name: cfe_blank_network
